### ISSUE TITLE
Teammate

### ISSUE THREAD

**Issue by 3lna7** [swsnu/swppfall2021#12]
Hello Everyone!

I was wondering is there someone who still could not make a team? or a team who needs a member?

Please contact me here or on ETL and we can talk about it.

Thank you.

**Comment by bumkyu00** [comment]
Hi, I'm Bumkyu Park.
I'm currently in a team of 3 people.
If you'd like to join, please contact to my kakaotalk.
Kakaotalk id: bumkyu00
