### ISSUE TITLE
Questions about final exam

### ISSUE THREAD

**Issue by ssubinsong** [swsnu/swppfall2021#159]
I have some questions for the final exam:

**1. Is it mandatory to use Python `virtualenv` in the exam?**
	  The LAB slides tell us to use the Python virtualenv when using Django. However, to be honest, I've barely used virtualenv in the assignments/project so far, so I'm not familiar with it. Is it mandatory to use the Python virtualenv when using Django/python in the exam? Or is it okay even if we just use the pre-installed version of Python, without virtualenv?

**2. Can we use Redux Toolkit in the exam?**
	I'm aware that no third party libraries are allowed in the exam. However, [Redux Toolkit is an "official" library distributed by the Redux team](https://github.com/reduxjs/redux-toolkit), and the official Redux docs [strongly recommends developers to use Redux Toolkit when writing Redux logic.](https://redux.js.org/style-guide/style-guide#use-redux-toolkit-for-writing-redux-logic) So, will it be possible to use Redux Toolkit in the exam?

I'll be waiting for your kind reply. Thank you.

**Comment by kdh0102** [comment]
1. We will install `virtualenv` and required packages for each student, so you do not have to worry about which `python` you use.
2. Redux toolkit is included in the environment.

**Comment by clarkindy** [comment]
> 1. We will install `virtualenv` and required packages for each student, so you do not have to worry about which `python` you use.

Does this mean we could use any version of Python we want? If not, what versions of Python are allowed? I am asking this question because I think the availability of various features are quite different between minor versions of Python.

**Comment by ttoru96** [comment]
@clarkindy
We will install Python of version 3.7.x and you will be asked to use this version of Python only. This is the version that we've been using throughout the practice sessions so you will find it familiar. 

If you come to the rehearsal, you will be able to do a hands-on check on the final exam environment, so please come if the time suits you :)

**Comment by kdh0102** [comment]
@clarkindy We will install Python 3.7.12 and the same version is used for the grading.
