### ISSUE TITLE
Looking for 1 more member

### ISSUE THREAD

**Issue by ellenk7** [swsnu/swppfall2021#19]
Hello, my name is Ellen Kim and we are currently looking for just 1 more person to be in our team. The other members are Jennie Kim and 길광연. To give a little background on ourselves we have worked with Python, JavaScript, HTML, AWS, mySQL, and also have experience with deployment.
Please let us know by replying to this comment if anyone is interested. Thank you and looking forward to working with you!

**Comment by TeddyAdamK** [comment]
Hi! My name is Teddy and I'm looking for a team!
Are you still looking for one member?

**Comment by ellenk7** [comment]
Yes, would you be able to tell us your Kakao ID so we can add you to the group chat?

**Comment by ellenk7** [comment]
Team member found!
