### ISSUE TITLE
Can we use the Bootstrap & React-Bootstrap framework in the project?

### ISSUE THREAD

**Issue by lemonshushu** [swsnu/swppfall2021#49]
Dear TAs, 

In order to make our project's design more sleek, and implement responsive design in an easier way, I wonder if we can use frameworks like Bootstrap and React-Bootstrap.
Would this be possible, or should we implement the UI only with raw CSS?

For further reference, 
- Bootstrap : https://getbootstrap.com
- React-Bootstrap : https://react-bootstrap.github.io

Thank you.

Best, 
Subin Song

**Comment by kdh0102** [comment]
Yes, you can use both in your project.
